### ISSUE TITLE
Why not read in the mouse speed directly 

### ISSUE THREAD

**Issue by gchriz** [raspberrypi-ui/lxinput#7]
In _read_mouse_speed (void)_ the mouse speed is read from the desktop configuration file written by the last run of lxinput.

But why not read it from the mouse directly? It may have been changed from elsewhere in the meantime...

In the shell it could be done like this, for example:

`xinput --list-props "PixArt USB Optical Mouse" | grep "libinput Accel Speed (" | sed -e 's/^.*:\s*//'`

---

(The usage of that config file _~/.config/autostart/LXinput-setup.desktop_ is indeed a bit strange, IMHO.)

**Comment by spl237** [comment]
Now implemented - thank you for the suggestion!
